name: iFit
description: O iFit vai mudar o seu jeito de treinar!
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  fluttertoast: ^8.2.11
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.3
  get: ^4.7.2
  hexagon: ^0.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/imgs/icons/app_icon.png" # Caminho para o Ã­cone
  adaptive_icon_background: "#FFFFFF" # Cor de fundo para Android

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - lib/imgs/
     - lib/imgs/exs/
     - lib/imgs/icons/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Avatar
      fonts:
        - asset: lib/fonts/VAL.otf
